feat: Add rain based on points amount.
tonkku107/poop-clicker pull request #4
Opened 2020-10-04 18:02 UTC by KararTY

Preview:
![image](https://user-images.githubusercontent.com/13697809/95023282-7f83fd80-067c-11eb-96b1-cc13ba59055a.png)

2020-10-04 20:01 UTC, tonkku107 requested changes

2020-10-04 20:01 UTC, tonkku107 commented on changelog.html
> +*Added switch for rain feature<br>
Would make more sense if these two were in reverse order

2020-10-04 20:01 UTC, tonkku107 commented on index.html
> -        	<small style="top: 0px;">Based on <a href="http://kararty.itch.io/poopclicker">KararTY's poopclicker</a> • Made by tonkku107 • <a href="https://github.com/tonkku107/poop-clicker">Fork on Git
You don't want credit anymore? :(

2020-10-04 20:01 UTC, tonkku107 commented on script.js
> +      rain = ret.rain || true;
This would always result in true

2020-10-04 20:01 UTC, tonkku107 commented on script.js
> +      canvas.width = 1920;
What about wider monitors?

2020-10-04 20:01 UTC, tonkku107 commented on script.js
> +        for (let index = 0; index < particles.length; index++) {
could be `for (const particle of particles)`

2020-10-04 20:01 UTC, tonkku107 commented on script.js
> +          if (particles[index] == null) {
`if (!particles[index])` or `if (!particle)`

2020-10-04 20:05 UTC, KararTY commented on index.html
> -        	<small style="top: 0px;">Based on <a href="http://kararty.itch.io/poopclicker">KararTY's poopclicker</a> • Made by tonkku107 • <a href="https://github.com/tonkku107/poop-clicker">Fork on Git
I'm a project contributor now, that's enough credit.

2020-10-05 19:41 UTC, tonkku107 commented on script.js
> +      rain = ret.rain || true;
Are you sure you want to default it to false now?

2020-10-10 17:18 UTC, tonkku107 approved these changes

2020-10-15 14:31 UTC, merged